title: rdwy.org
description: "My anonymous musings"
url: http://rdwy.org
author: rdwy

theme: jekyll-theme-cayman

plugins:
    - jekyll-paginate
    - jemoji
    - jekyll-feed
    
paginate: 8
paginate_path: "/:num/"